### ISSUE TITLE
module aardwolf

### ISSUE THREAD

**Issue by dottpannunzio** [lefayjey/linWinPwn#7]
hi,
i have this problem with my Kali ...
can you halp me?

[+] lun 16 gen 2023, 09:30:12, CET
Traceback (most recent call last):
  File "/usr/bin/crackmapexec", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/cme/crackmapexec.py", line 117, in main
    args = gen_cli_args()
  File "/usr/lib/python3/dist-packages/cme/cli.py", line 76, in gen_cli_args
    protocol_object = p_loader.load_protocol(protocols[protocol]['path'])
  File "/usr/lib/python3/dist-packages/cme/loaders/protocol_loader.py", line 15, in load_protocol
    protocol = imp.load_source('protocol', protocol_path)
  File "/usr/lib/python3.10/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/cme/protocols/rdp.py", line 10, in <module>
    from aardwolf import logger
ModuleNotFoundError: No module named 'aardwolf'
[-] Error connecting to target! Please ensure the target is a Domain Controller and try again...

**Comment by MartinSly** [comment]
Same here

**Comment by lefayjey** [comment]
Both errors seem to be related to the installation of "crackmapexec". What's the output you get when you run "crackmapexec"? 
I've also updated the `install.sh` script to fix the installation of crackmapexec using pipx. 

Can you try running the latest `install.sh` as kali user, and see if you have the same issue?

**Comment by dottpannunzio** [comment]
Hello,
Thanks for the reply. Tried new install.sh but didn't fix. I then uninstalled crackmapexec and deleted the configuration folder. I reinstalled manually following this procedure:
https://wiki.porchetta.industries/getting-started/installation/installation-on-unix
problem solved!
thank you
